### ISSUE TITLE
The error persists

### ISSUE THREAD

**Issue by HanielCota** [mecperspicace/SkinChangerAPI#2]
![image](https://user-images.githubusercontent.com/117860225/212766178-b76ec040-bac9-4f81-aa36-f7e2d01607dd.png)
![image](https://user-images.githubusercontent.com/117860225/212766201-967cb311-8b92-43ab-bdd5-83e19683e463.png)

**Comment by HanielCota** [comment]
O erro "Not a JSON Object: null" geralmente ocorre quando o código tenta acessar uma propriedade de um objeto JSON nulo. Isso pode acontecer se o objeto retornado pela API da Mojang for nulo ou se o conteúdo retornado não puder ser parseado corretamente para um objeto JSON.

**Comment by peepsii** [comment]
Can you send me the full code please.

**Comment by HanielCota** [comment]
Yes! I haven't touched anything in your api class, I've updated it and everything, but the error still persists
The error is in your api

My Discord to contact-me Fialhão#6186

![image](https://user-images.githubusercontent.com/117860225/212770899-8338d10f-2ffe-441b-a161-3a86793d8a30.png)

**Comment by peepsii** [comment]
This is the first time I've seen this, I'll look at it tomorrow, thanks

**Comment by peepsii** [comment]
I try to fix it in a659b1b5f1c04f8f62ead1313aa405e9951d5e4e, let me know if it works because I can test it now. Thanks...
